#OPENAI_API_KEY = "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"
OPENAI_API_KEY = ""
ASSISTANT_ID = None
UPLOAD_FOLDER="uploaded_images"
STATE_FOLDER="state_data"
SCIEBO_USERNAME="murtaza.fakhruddin@tu-dortmund.de"
SCIEBO_PASSWORD="" #this is app password
SCIEBO_APPNAME="medical_ai"
SCIEBO_IMAGE_BASEURL= f"https://tu-dortmund.sciebo.de/remote.php/dav/files/{SCIEBO_USERNAME}/medical_ai/images/"
SCIEBO_STATE_BASEURL= f"https://tu-dortmund.sciebo.de/remote.php/dav/files/{SCIEBO_USERNAME}/medical_ai/state_data/"
